using DataStructuresAndAlgorithms.Comparison;

//CompareIterationVsRecursion.CompareIterationVsRecursionForPrintNumbers(1000);
//CompareIterationVsRecursion.CompareIterationVsRecursionForSumOfNumbers(1000);
CompareTreeVsTailRecursion.CompareTreeVsTailRecursionForSumOfNumbers(1000);