using DataStructuresAndAlgorithms.Comparison;
using DataStructuresAndAlgorithms.Iteration;
using Recursions = DataStructuresAndAlgorithms.Recursion;

//CompareIterationVsRecursion.CompareIterationVsRecursionForPrintNumbers(1000);
//CompareIterationVsRecursion.CompareIterationVsRecursionForSumOfNumbers(1000);
CompareTreeVsTailRecursion.CompareTreeVsTailRecursionForSumOfNumbers(10);