using DataStructuresAndAlgorithms.Search;

//CompareIterationVsRecursion.CompareIterationVsRecursionForPrintNumbers(1000);
//CompareIterationVsRecursion.CompareIterationVsRecursionForSumOfNumbers(1000);
//CompareTreeVsTailRecursion.CompareTreeVsTailRecursionForSumOfNumbers(1000);

LinearSearch.ExecuteSearch();